name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: apt-install-pip
        run: apt install python3-pip
      - name: pip-install-depenency
        run: pip3 install -r https://raw.githubusercontent.com/Eric-lightning/basis-learning/master/mkdocs.yml
      - name: deploy
        run: mkdocs gh-deploy
