name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - documents

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: FIX GCCないのでいんす子
        run: sudo apt-get install gcc
      - name: documentブランチから
        uses: actions/checkout@v2
        with:
          ref: documents
      - name: masterへでぷろい
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
