name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - documents

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-18.04
    steps:
      # シンボリックリンクを扱えるようGitを設定する
      - name: Git config
        run: |
          git config --global core.symlinks true
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com

      # リポジトリをチェックアウトする
      # MkDocsでgit-revision-dateプラグインを利用している場合は、
      # 全てのコミット履歴をfetchする(fetch-depth: 0)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # submoduleをcloneする
      # docsフォルダ内にsubmoduleへのsymlinkが含まれるため、restoreする
      - name: Checkout submodules
        run: |
          git submodule init
          git submodule update
          rm -r docs
          git restore docs

      # Python3.8をセットアップ
      - name: Set up Python
        run: |
          sudo apt install python3 python3-pip
          sudo pip install mkdocs mkdocs-material

      # MkDocsでGitHubへデプロイする
      - name: MkDocs Deploy
        env:
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
        run: |
          git fetch --depth=1 origin master
          poetry run mkdocs gh-deploy
